import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    'react/index': 'src/react/index.ts',
    'vanilla/index': 'src/vanilla/index.ts',
    'adapters/index': 'src/adapters/index.ts',
    'adapters/evm': 'src/adapters/evm.ts',
    'adapters/sui': 'src/adapters/sui.ts',
    'adapters/near': 'src/adapters/near.ts',
    'adapters/aptos': 'src/adapters/aptos.ts',
    'adapters/starknet': 'src/adapters/starknet.ts',
    'adapters/ton': 'src/adapters/ton.ts',
    'adapters/tron': 'src/adapters/tron.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  external: [
    'react',
    'react-dom',
    '@reown/appkit',
    '@reown/appkit/react',
    '@reown/appkit/networks',
    '@reown/appkit-adapter-wagmi',
    '@reown/appkit-adapter-solana',
    'wagmi',
    'wagmi/chains',
    'viem',
    '@tanstack/react-query',
    '@mysten/dapp-kit',
    '@hot-labs/near-connect',
    '@aptos-labs/wallet-adapter-react',
    '@starknet-react/core',
    '@starknet-react/chains',
    '@tonconnect/ui-react',
    '@tronweb3/tronwallet-adapter-react-hooks',
    '@tronweb3/tronwallet-adapters',
  ],
  banner: {
    js: '"use client";',
  },
});
